### ISSUE TITLE
Error Undefined Symbol running in iOS simulator

### ISSUE THREAD

**Issue by senthil-asdra** [RazerMS/rms-mobile-xdk-flutter#10]
Got below error while debug in iOS simulator

Error (Xcode): Undefined symbol: _$sSo20PKMerchantCapabilityV7PassKitE13capability3DSABvgZ

Error (Xcode): Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56

Using rms_mobile_xdk_flutter: ^3.33.7 in flutter app.
Xcode version is 14.2
Xcode build error:
Undefined symbols for architecture x86_64:
  "_$sSo20PKMerchantCapabilityV7PassKitE13capability3DSABvgZ", referenced from:
      _$s9MOLPayXDK9APManagerC12startPayment10completionyySbc_tF in MOLPayXDK(APManager.o)
  "__swift_FORCE_LOAD_$_swiftCompatibility56", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_MOLPayXDK in MOLPayXDK(APManager.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility56_$_MOLPayXDK)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please throw some light on this.

**Comment by apis17** [comment]
please use latest version here: https://pub.dev/packages/fiuu_mobile_xdk_flutter
