### ISSUE TITLE
Null Safety Migration 

### ISSUE THREAD

**Issue by momoDragon** [RazerMS/rms-mobile-xdk-flutter#2]
Dear team,
Most flutter projects and packages are moving to Null Safety.
https://dart.dev/null-safety/migration-guide

Are there any plans to migrate this xdk to Null Safety compatible? 
rms_mobile_xdk_flutter: ^3.30.0
https://pub.dev/packages/rms_mobile_xdk_flutter
<img width="1140" alt="Screenshot 2021-04-21 at 7 35 32 PM" src="https://user-images.githubusercontent.com/40727575/115547621-0dea6480-a2d9-11eb-9972-c315afad2d89.png">

**Comment by wasddsaw** [comment]
Hi @momoDragon , we already update package to null safety, rms_mobile_xdk_flutter: ^3.30.1

https://pub.dev/packages/rms_mobile_xdk_flutter
