### ISSUE TITLE
iOS problem about the swipe dismiss the plugin

### ISSUE THREAD

**Issue by yenyichau** [RazerMS/rms-mobile-xdk-flutter#3]
Hi, I notice that when I use the iOS swipe dismiss method it doesn't return any response about the transaction. So far only the close button got return the response right now.

**Comment by hisyamadzha** [comment]
Yes, because it has no listener on that event.

**Comment by yenyichau** [comment]
can you guys add a listener on this swipe dismiss event? thanks.
