### ISSUE TITLE
MPMainUIWebClient mptransactionresults dataString = {"Error":"Communication Error, please check internet connection, username, or password"} D/MOLPAY  ( 9441): MPMainUIWebClient jsonResult = {"Error":"Communication Error, please check internet connection, username, or password"}

### ISSUE THREAD

**Issue by samaliftech** [RazerMS/rms-mobile-xdk-flutter#4]
**Describe the bug**
Wrong Username or password. I followed he detail that come from email that used for Razer Merchant Service but it said wrong username or password.

This error throws:
```
MPMainUIWebClient mptransactionresults dataString = {"Error":"Communication Error, please check internet connection, username, or password"}
D/MOLPAY  ( 9441): MPMainUIWebClient jsonResult = {"Error":"Communication Error, please check internet connection, username, or password"}

```

**Expected behavior**
Username and Password are true 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version [e.g. 22
 - 
**Smartphone (please complete the following information):**
 - Device: Redmi Note 5 Pro
 - OS: Android 10
 - Browser Chrome

**Additional context**

**Comment by wasddsaw** [comment]
Hi @samaliftech , you may email us at [support-sa@razer.com](mailto:support-sa@razer.com)
