### ISSUE TITLE
Problem when decode JsonResult from MPMainWebClient

### ISSUE THREAD

**Issue by samaliftech** [RazerMS/rms-mobile-xdk-flutter#5]
Hi. I have a problem when decode JsonResult from MPMainWebClient, the flutter can't define success or failed transaction. Need help as soon as possible

**Comment by wasddsaw** [comment]
hi @samaliftech , you may send your issue at [support-sa@razer.com](mailto:support-sa@razer.com) and kindly provide with any screen record, screenshoot  or logs for us to troubleshooting.
