### ISSUE TITLE
build release APK couldnt launch razer pay

### ISSUE THREAD

**Issue by LtotheWT** [RazerMS/rms-mobile-xdk-flutter#7]
**Describe the bug**
build debug APK  can launch razer pay
build release APK cannot launch razer pay

**To Reproduce**
build apk --release

**Expected behavior**
able to launch razer pay

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
rms_mobile_xdk_flutter: ^3.32.4
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.5 21G72 darwin-arm, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by apis17** [comment]
please use latest version: https://pub.dev/packages/fiuu_mobile_xdk_flutter
