### ISSUE TITLE
show only e wallet for mp_channel 

### ISSUE THREAD

**Issue by LtotheWT** [RazerMS/rms-mobile-xdk-flutter#8]
**Is your feature request related to a problem? Please describe.**
for now i need to set mp_allowed_channels to show only e wallet 

**Describe the solution you'd like**
set mp_channel to something like e-wallet to show all e wallet

**Describe alternatives you've considered**

**Additional context**

**Comment by wasddsaw** [comment]
hi @LtotheWT , mobile XDK currently do not have filtering feature like you suggested. Only 2 options:-

- use express_mode = true, which is use your own ui
- use mp_allowed_channels parameter
