### ISSUE TITLE
Unable to lauch app on mac m2

### ISSUE THREAD

**Issue by li9ht** [RazerMS/rms-mobile-xdk-flutter#9]
**Describe the bug**
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Xcode build done.                                           10.2s
Failed to build iOS app
Error (Xcode): Building for 'iOS-simulator', but linking in object file (/Users/fird/flutter/razertest/bug1/ios/Pods/rms-mobile-xdk-cocoapods/MOLPayXDK.framework/Versions/A/MOLPayXDK[arm64][2](MOLPayWebview.o)) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.

**To Reproduce**
1 . Create new flutter app
2.  flutter pub add rms_mobile_xdk_flutter
3.  Run -> Start Debugging
4.  Error

**Expected behavior**
Lauch app

**Screenshots**

**Development ENV:**
 - OS: Sonoma 14.2.1, 
 - Chip : Apple M2 Max

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro emulator
 - OS: iOS 17.2
 - Browser -
 - Version -

**Additional context**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

**Comment by apis17** [comment]
please use latest version here: https://pub.dev/packages/fiuu_mobile_xdk_flutter
